### ISSUE TITLE
[BUG] ServerBooster generated an exception java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by CitizenPrayer** [PluginBugs/Issues-ServerBooster#64] opened 2022-10-07 17:22 UTC
Not sure why this is going on, but can anyone help please?

I'm running Paper 1.19.2 (just switched from Spigot 1.19.2). I'm using Auto Plug (https://autoplug.one/), which in their config automatically chooses the build version, as you can see in this picture. I understand that several users have experienced this issue, and the resolution has been to download the latest version of Paper. This won't work for me, as I'm using the Jar file given by AutoPlug, and they automatically pull down the latest Paper version. I think the solution here is not to pass off updating to the end user or another dev team, when it's your own code that's throwing exceptions, demanding an absolute "latest version". Now, this may not be entirely correct, or correct at all, but AutoPlug is not throwing the error, ServerBooster is.

![image](https://user-images.githubusercontent.com/10674301/194614370-50b9c398-d527-43aa-9afd-bdcb84679280.png)

! [Fri 16:07:29 WARN  ServerBooster] Task #99 for ServerBooster v1.1.3 generated an exception
java.lang.NoSuchFieldError: P
    at ServerBooster_1.1.3.jar//dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.tasks.EntitiesOptimizerProcess.a(SourceFile:127)
    at ServerBooster_1.1.3.jar//dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.tasks.EntitiesOptimizerProcess.run(SourceFile:71)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LoneDev6** [comment] 2022-10-11 10:18
Duplicate of https://github.com/PluginBugs/Issues-ServerBooster/issues/62

**Closed by LoneDev6** 2022-10-11 10:18 UTC
Labels: bug
