### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Tenet70** [PluginBugs/Issues-ServerBooster#65] opened 2022-10-10 19:04 UTC
Paper 1.19.1
plugins - protocollib, lonelibs,serverbooster newest update 1.1.3

I only join the server and it spams this,
Console
12:00:39

java.lang.NoSuchFieldError: P
at dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.tasks.EntitiesOptimizerProcess.a(SourceFile:127) ~[ServerBooster_1.1.3.jar:?]
at dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.tasks.EntitiesOptimizerProcess.run(SourceFile:71) ~[ServerBooster_1.1.3.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-201]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-201]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

WARN
12:00:42

[ServerBooster]: Task #5 for ServerBooster v1.1.3 generated an exception

Console
12:00:42

java.lang.NoSuchFieldError: P
at dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.tasks.EntitiesOptimizerProcess.a(SourceFile:127) ~[ServerBooster_1.1.3.jar:?]
at dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.tasks.EntitiesOptimizerProcess.run(SourceFile:71) ~[ServerBooster_1.1.3.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-201]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-201]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-201]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LoneDev6** [comment] 2022-10-11 10:18
Duplicate of https://github.com/PluginBugs/Issues-ServerBooster/issues/62

**Closed by LoneDev6** 2022-10-11 10:18 UTC
Labels: bug
